/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package todolist;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class telas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telas.class.getName());
    
    DefaultTableModel model;
    
    private static final String CONCLUIDA = "Concluída";
    private static final String NAO_CONCLUIDA = "Não concluída";
    
    private final ArrayList<String> tarefas = new ArrayList<>();
    private final ArrayList<String> tarefasFiltradas = new ArrayList<>();
    
 
    /**
     * Creates new form telas
     */
    public telas() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        model = (DefaultTableModel) jTableTarefas.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldDescricaoTarefa = new javax.swing.JTextField();
        jComboBoxFiltroStatus = new javax.swing.JComboBox<>();
        jButtonAdicionarTarefa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTarefas = new javax.swing.JTable();
        jButtonConcluirTarefa = new javax.swing.JButton();
        jButtonRemoverTarefa = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxFiltroStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Concluído", "Não concluído" }));

        jButtonAdicionarTarefa.setText("adicionar");
        jButtonAdicionarTarefa.addActionListener(this::jButtonAdicionarTarefaActionPerformed);

        jTableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tarefa", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableTarefas);

        jButtonConcluirTarefa.setText("Concluir");
        jButtonConcluirTarefa.addActionListener(this::jButtonConcluirTarefaActionPerformed);

        jButtonRemoverTarefa.setText("Remover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldDescricaoTarefa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdicionarTarefa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonConcluirTarefa)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemoverTarefa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(424, Short.MAX_VALUE))))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarTarefa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConcluirTarefa)
                    .addComponent(jButtonRemoverTarefa))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConcluirTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirTarefaActionPerformed
    
    }//GEN-LAST:event_jButtonConcluirTarefaActionPerformed

    private void jButtonAdicionarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarTarefaActionPerformed
        if (jTextFieldDescricaoTarefa.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, " A descrição da tarefa não pode ser vazia");
 
 
        return;     
        
    }    
    
       if(hasTarefaRepetida(jTextFieldDescricaoTarefa.getText())){
           JOptionPane.showMessageDialog(null, "A tarefa " + jTextFieldDescricaoTarefa.getText() + "Já existe!");
           return;
           
       }
        
       tarefas.add(jTextFieldDescricaoTarefa.getText() + ";" + NAO_CONCLUIDA);
       preencherTabela();
       
       jTextFieldDescricaoTarefa.setText("");
    }//GEN-LAST:event_jButtonAdicionarTarefaActionPerformed

    public boolean hasTarefaRepetida(String novaTarefa){
        for (String tarefa : tarefas){
            String dados[] = tarefa.split(";");
            if (novaTarefa.toLowerCase().equals(dados[0].toLowerCase())){
                return true;
            }
        }
         
        return false;
    }
    
    private void preencherTabela(){
        ArrayList<String> listaTarefas;
        
        if (jComboBoxFiltroStatus.getSelectedIndex() > 0){
            listaTarefas = tarefasFiltradas;
        }else{
          listaTarefas = tarefas;
          
        }
        
        model.setRowCount(0);
        
        for (String tarefa : listaTarefas){
            String[] dados = tarefa.split((";"));
            
            model.addRow(new Object[]{
                dados[0],
                dados[1]
            });
            
            }
        }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarTarefa;
    private javax.swing.JButton jButtonConcluirTarefa;
    private javax.swing.JButton jButtonRemoverTarefa;
    private javax.swing.JComboBox<String> jComboBoxFiltroStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableTarefas;
    private javax.swing.JTextField jTextFieldDescricaoTarefa;
    // End of variables declaration//GEN-END:variables
}
